/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.rjzd.aistock.api;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * -----------------------------------------about AI domain  start -----------------------------------
 * AI 机器人策略
 * 
 */
public enum AIIncomeType implements org.apache.thrift.TEnum {
  LATEST_INCOME_WEEK(7),
  LATEST_INCOME_MONTH(30),
  INCOME_TOTAL(10);

  private final int value;

  private AIIncomeType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static AIIncomeType findByValue(int value) { 
    switch (value) {
      case 7:
        return LATEST_INCOME_WEEK;
      case 30:
        return LATEST_INCOME_MONTH;
      case 10:
        return INCOME_TOTAL;
      default:
        return null;
    }
  }
}
