/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.rjzd.aistock.api;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * K线类型  日K   周k   月k
 * 
 */
public enum KType implements org.apache.thrift.TEnum {
  REALTIME(0),
  M5(1),
  M15(2),
  M30(3),
  M60(4),
  DAY(5),
  WEEK(6),
  MONTH(7);

  private final int value;

  private KType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static KType findByValue(int value) { 
    switch (value) {
      case 0:
        return REALTIME;
      case 1:
        return M5;
      case 2:
        return M15;
      case 3:
        return M30;
      case 4:
        return M60;
      case 5:
        return DAY;
      case 6:
        return WEEK;
      case 7:
        return MONTH;
      default:
        return null;
    }
  }
}
